### ISSUE TITLE
`suggest!` is not aware of verbosity level

### ISSUE THREAD

**Issue by wupr** [autobib/autobib#110]
`suggest!` usually follows an `error!` or `warn!`, but unlike the latter two, it cannot be quieted by `-q` or `-qq`.

**Comment by wupr** [comment]
Related to this: in the `autobib delete` confirmation, the referencing keys are printed to stderr but the confirmation prompt is in stdout. It might be good to use just one of stderr and stdout.

**Comment by alexrutar** [comment]
Good point, we should definitely be using STDERR for everything that is not program output.

Maybe the easiest way to fix the `suggest!` thing is to use [`log_enabled!`](https://docs.rs/log/latest/log/macro.log_enabled.html) to check for at least `warning` verbosity before printing. In the future I guess we could also suppress this using some config option / environment variable.
