### ISSUE TITLE
CLI improvements

### ISSUE THREAD

**Issue by wupr** [autobib/autobib#89]
Currently, starting with no `local:wu_2024` in the database:
```
% autobib local wu_2024                   
% autobib edit wu_2024
ERROR Cannot edit null record 'wu_2024'
% autobib local wu_2024
```

Several possible improvements here:

- [x] ~~Set the default verbosity level to `INFO` and add some more messages?~~ E.g. `autobib local` could say that `local:wu_2024` has been created (or it already exists), as a reminder that `wu_2024` is not the full id.
- [x] Automatically create an alias `wu_2024` with `autobib local wu_2024`, with an optional `--no-alias` flag?
- [x] `autobib local` should open the editor if neither `--from <FILE>` nor `--no-edit` is supplied.
- [x] `autobib edit` should say "Cannot edit non-existent record" as "null record" has a specific meaning.

**Comment by alexrutar** [comment]
Here's another possible improvement: `autobib local wu_2024` automatically creates *two* records: an internal `local:wu_2024`, and then an alias `wu_2024` which points two it.

**Comment by alexrutar** [comment]
I think the second option is the best! It seems to be the version which "just works".

**Comment by alexrutar** [comment]
Also, I think we could default to running `--edit` (i.e. as you say having a `--no-edit` option).
