### ISSUE TITLE
`autobib update` improvements

### ISSUE THREAD

**Issue by alexrutar** [autobib/autobib#91]
- [ ] Add some sort of update-mode option to update, to either: (1) prefer local, (2) prompt for changes from remote, or (3) prefer remote
- [ ] Add `--from` option for update, to read the 'update' data from a local bibtex file

**Comment by wupr** [comment]
Another option is to identify fields that have been manually edited using the change log, give the user the choice on what to do, but overwrite everything else.

**Comment by wupr** [comment]
This would require remembering in the change log which changes arise from the user.

**Comment by alexrutar** [comment]
I just realized that the update logic is wrong: what happens if the record is present in the `NullRecords`? We should still still run the update code, and if the record ends up being not null, then the `NullRecords` row should be deleted and the new contents added to the database.
