### ISSUE TITLE
Clap errors inconsistent in style with our errors

### ISSUE THREAD

**Issue by wupr** [autobib/autobib#96]
_Originally posted by @alexrutar in https://github.com/autobib/autobib/issues/94#issuecomment-2426577872_:

```
cargo run -- alias add 'doi:10.1016/0021-8693(85)90145-0' alias
```
[Clap] is processing the errors up-front (during argument parsing) and immediately complaining about the function signature. It's just a bit confusing that it is formatted as `error:` I guess the best way to fix this is (1) figure out how to reformat clap error message formatting; and then (2) not print the citation key twice.

**Comment by alexrutar** [comment]
From: https://github.com/autobib/autobib/pull/98#discussion_r1813815642

We can also make our message headings boldface and lower case. But we still need to deal with clap inserting an extra `:` (or do that ourselves, too).
